### ISSUE TITLE
Cambiarle el nombre a la clase Refugio

### ISSUE THREAD

**Issue by alaniv** [ManuMarcos/Sistema-de-Gestion-Adopciones#2]
Razón: se puede malinterpretar como una clase "Sistema". 
Ver última clase de la materia (06/09) para una posible implementación de como simular persistencia

**Comment by ManuMarcos** [comment]
Sisi cuando la arme pense lo mismo, pero no hay otra forma de almacenar esos objetos que no sea en una clase y que haya una sola instancia de esta. En la ultima clase lo hizo de la misma forma si no me equivoco, por ahi le podemos cambiar el nombre para que quede mejor. Despues vuelvo a mirar la ultima clase y me fijo bien

**Comment by alaniv** [comment]
![image](https://github.com/ManuMarcos/Sistema-de-Gestion-Adopciones/assets/26285379/feb8dec8-8697-4dfc-a319-0abd29eba919)

Es al final de la clase que lo menciona. Lo pone en la clase model, como un static list. Yo copié esa forma.

**Comment by alaniv** [comment]
El Dao entiendo que no hace falta.
