### ISSUE TITLE
Menú Alarmas - arreglar navegación

### ISSUE THREAD

**Issue by alaniv** [ManuMarcos/Sistema-de-Gestion-Adopciones#9]
Hay algo raro al entrar y salir del Menú de alarmas. Navegando un poco se reproduce.

**Comment by Mon-Zai** [comment]
Que ocurre exactamente? probé entrar y salir pero nada.

**Comment by alaniv** [comment]
Ahí te digo los pasos, bancame que pruebo. 
Me parece que es por los return menu_principal, que están duplicando el menu en el stack de pantallas. Capaz un return stay va. Pero esperame que pruebo y te digo los pasos

**Comment by alaniv** [comment]
Login > 2 Ingresamos.
Main Menu > 2 vamos a alarmas
Alarmas > 1 crear alarma, la creamos
(*) Main Menu > 6 log out
Menu Alarmas.  => BUG: tendría que haber ido a pantalla Login con el log out.

(*) acá para seguir la lógica del resto de pantallas, creo que tendría que quedarse en Alarmas y no ir al menu

**Comment by Mon-Zai** [comment]
Dale ya lo probé, si se arregla con el stay, también hare para que se quede en Alarmas

**Comment by alaniv** [comment]
También había un tema al elegir el animal, pero ví que lo tenías corregido en la versión que compartiste al mediodía. un break que faltaba en un for.
